name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "Rahul Deshar"
          git config --global user.email "desarrahul@gmail.com"
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git --work-tree dist commit -m "GitHub Actions: Build and deploy to gh-pages"
          git push origin HEAD:gh-pages --force

      - name: Clean up
        run: |
          git checkout main
          git branch -D gh-pages


